import {
  Heart, PawPrint, ShieldCheck, Baby, Users, Palette, Accessibility,
  GraduationCap, Briefcase, Leaf, Home, Stethoscope, Ear, Bed,
  Building2, HandHeart, Globe2, BookOpen, Microscope, Pill,
  Brain, Plane, Church, Truck, UsersRound, Dumbbell, Eye,
} from 'lucide-react'

export interface Category {
  slug: string
  name: string
  tagline: string
  description: string
  icon: any
  color: string
  bgColor: string
  ringColor: string
  problem: string
  approach: string[]
  budgetAllocation: { label: string; pct: number; color: string }[]
  stats: { label: string; value: string }[]
  countries: string[]
  goalAmount: number
  raisedAmount: number
}

export const categories: Category[] = [
  {
    slug: 'aged',
    name: 'Aged Care',
    tagline: 'Honouring elders with dignity, care, and community',
    description: 'Supporting elderly Africans with healthcare, nutrition, social inclusion, and age-friendly infrastructure in communities where formal pension systems barely exist.',
    icon: Heart,
    color: 'text-rose-600',
    bgColor: 'bg-rose-50',
    ringColor: 'ring-rose-100',
    problem: 'Over 70 million people aged 60+ live in Africa, most without pensions, healthcare, or social safety nets. Elderly Africans frequently become primary caregivers for orphaned grandchildren while managing chronic illness themselves.',
    approach: [
      'Community-based elder care networks across rural villages',
      'Monthly nutrition parcels and chronic disease management',
      'Intergenerational programmes pairing elders with youth for cultural preservation',
      'Legal advocacy for age-friendly policies and pension access',
    ],
    budgetAllocation: [
      { label: 'Direct elder support', pct: 55, color: 'bg-rose-500' },
      { label: 'Healthcare & nutrition', pct: 25, color: 'bg-rose-400' },
      { label: 'Programme admin', pct: 12, color: 'bg-rose-300' },
      { label: 'Fundraising', pct: 8, color: 'bg-rose-200' },
    ],
    stats: [
      { label: 'Elders supported', value: '3,200+' },
      { label: 'Nutrition parcels delivered', value: '28,000' },
      { label: 'Care networks active', value: '45' },
    ],
    countries: ['Kenya', 'Tanzania', 'South Africa', 'Uganda', 'Ghana'],
    goalAmount: 300000,
    raisedAmount: 185000,
  },
  {
    slug: 'animals',
    name: 'Animal Welfare',
    tagline: 'Protecting wildlife and supporting livelihoods alongside nature',
    description: 'Combining wildlife conservation with community development — because protecting Africa\'s extraordinary biodiversity also means protecting the people who live alongside it.',
    icon: PawPrint,
    color: 'text-amber-600',
    bgColor: 'bg-amber-50',
    ringColor: 'ring-amber-100',
    problem: 'Africa loses roughly 30,000 elephants and thousands of rhinos annually to poaching. Human-wildlife conflict destroys livelihoods as elephants raid crops and lions kill livestock. Communities living next to wildlife bear the highest cost of conservation.',
    approach: [
      'Community-managed wildlife corridors connecting fragmented habitats',
      'Compensation funds for crop raiding and livestock predation',
      'Anti-poaching ranger training and equipment provision',
      'Eco-tourism training creating income from living wildlife',
    ],
    budgetAllocation: [
      { label: 'Community compensation', pct: 40, color: 'bg-amber-500' },
      { label: 'Anti-poaching operations', pct: 25, color: 'bg-amber-400' },
      { label: 'Conservation training', pct: 20, color: 'bg-amber-300' },
      { label: 'Admin & fundraising', pct: 15, color: 'bg-amber-200' },
    ],
    stats: [
      { label: 'Communities protected', value: '62' },
      { label: 'Rangers trained', value: '340' },
      { label: 'Hectares conserved', value: '180,000' },
    ],
    countries: ['Kenya', 'Tanzania', 'South Africa', 'Zimbabwe', 'Botswana'],
    goalAmount: 500000,
    raisedAmount: 290000,
  },
  {
    slug: 'armed-and-ex-services',
    name: 'Armed Forces & Veterans',
    tagline: 'Restoring lives after conflict and service',
    description: 'Providing rehabilitation, psychosocial support, and reintegration services for ex-soldiers, peacekeepers, and victims of armed conflict across Africa.',
    icon: ShieldCheck,
    color: 'text-green-700',
    bgColor: 'bg-green-50',
    ringColor: 'ring-green-100',
    problem: 'Millions of Africans have been affected by decades of civil wars, insurgencies, and peacekeeping deployments. Veterans and ex-combatants face PTSD, disability, unemployment, and social stigma with virtually no state support.',
    approach: [
      'Trauma counselling and PTSD treatment through community health workers',
      'Vocational training and micro-loan programmes for reintegration',
      'Peer support groups for veterans and their families',
      'Advocacy for veteran benefits and recognition policies',
    ],
    budgetAllocation: [
      { label: 'Psychosocial support', pct: 35, color: 'bg-green-600' },
      { label: 'Vocational training', pct: 30, color: 'bg-green-500' },
      { label: 'Family support', pct: 20, color: 'bg-green-400' },
      { label: 'Admin & fundraising', pct: 15, color: 'bg-green-300' },
    ],
    stats: [
      { label: 'Veterans supported', value: '2,800+' },
      { label: 'Vocational placements', value: '1,200' },
      { label: 'Peer groups running', value: '38' },
    ],
    countries: ['Sierra Leone', 'Liberia', 'Rwanda', 'South Sudan', 'DRC'],
    goalAmount: 250000,
    raisedAmount: 120000,
  },
  {
    slug: 'children-and-youth',
    name: 'Children & Youth',
    tagline: 'Giving every child the chance to thrive',
    description: 'Protecting vulnerable children and empowering youth through education, nutrition, safe spaces, mentorship, and skills development across Africa.',
    icon: Baby,
    color: 'text-sky-600',
    bgColor: 'bg-sky-50',
    ringColor: 'ring-sky-100',
    problem: 'Africa has the world\'s youngest population — 60% under 25 — yet faces some of the highest rates of child mortality, malnutrition, child labour, and youth unemployment. An estimated 50 million children are orphaned, many due to HIV/AIDS.',
    approach: [
      'After-school programmes with tutoring, meals, and psychosocial support',
      'Child protection networks preventing abuse, exploitation, and child marriage',
      'Youth entrepreneurship boot camps and seed funding',
      'Safe spaces in urban slums and rural villages',
    ],
    budgetAllocation: [
      { label: 'Education & meals', pct: 40, color: 'bg-sky-500' },
      { label: 'Child protection', pct: 25, color: 'bg-sky-400' },
      { label: 'Youth empowerment', pct: 20, color: 'bg-sky-300' },
      { label: 'Admin & fundraising', pct: 15, color: 'bg-sky-200' },
    ],
    stats: [
      { label: 'Children reached', value: '15,000+' },
      { label: 'Youth trained', value: '4,500' },
      { label: 'Safe spaces active', value: '28' },
    ],
    countries: ['Nigeria', 'Kenya', 'Uganda', 'Ghana', 'Ethiopia'],
    goalAmount: 600000,
    raisedAmount: 410000,
  },
  {
    slug: 'community',
    name: 'Community Development',
    tagline: 'Building stronger communities from the ground up',
    description: 'Empowering local communities with infrastructure, governance support, clean energy, and economic development programmes designed and led by the communities themselves.',
    icon: Users,
    color: 'text-indigo-600',
    bgColor: 'bg-indigo-50',
    ringColor: 'ring-indigo-100',
    problem: 'Rural African communities often lack basic infrastructure — paved roads, electricity, clean water systems, and community centres. Without these foundations, education, health, and economic development remain out of reach.',
    approach: [
      'Community-led needs assessments and participatory planning',
      'Village infrastructure projects: solar power, boreholes, community centres',
      'Local governance strengthening and civic education',
      'Savings and loan groups building financial resilience',
    ],
    budgetAllocation: [
      { label: 'Infrastructure projects', pct: 45, color: 'bg-indigo-500' },
      { label: 'Community capacity building', pct: 25, color: 'bg-indigo-400' },
      { label: 'Micro-finance seed funds', pct: 15, color: 'bg-indigo-300' },
      { label: 'Admin & fundraising', pct: 15, color: 'bg-indigo-200' },
    ],
    stats: [
      { label: 'Communities served', value: '95' },
      { label: 'Solar installations', value: '42' },
      { label: 'Savings groups formed', value: '310' },
    ],
    countries: ['Tanzania', 'Mozambique', 'Malawi', 'Zambia', 'Rwanda'],
    goalAmount: 450000,
    raisedAmount: 280000,
  },
  {
    slug: 'culture-and-heritage',
    name: 'Culture & Heritage',
    tagline: 'Preserving Africa\'s rich traditions for future generations',
    description: 'Documenting, preserving, and celebrating Africa\'s diverse cultural heritage — from oral histories and traditional crafts to historic sites and indigenous knowledge systems.',
    icon: Palette,
    color: 'text-orange-600',
    bgColor: 'bg-orange-50',
    ringColor: 'ring-orange-100',
    problem: 'Africa\'s cultural heritage is disappearing rapidly due to urbanization, globalization, and conflict. Over 3,000 African languages are endangered. Traditional crafts, music, and oral histories are lost as elders pass without documenting them.',
    approach: [
      'Community heritage documentation projects using digital media',
      'Artisan cooperatives sustaining traditional crafts with market access',
      'Cultural festivals and exchange programmes connecting generations',
      'Heritage site protection and community-managed tourism',
    ],
    budgetAllocation: [
      { label: 'Documentation projects', pct: 30, color: 'bg-orange-500' },
      { label: 'Artisan support', pct: 30, color: 'bg-orange-400' },
      { label: 'Cultural programmes', pct: 25, color: 'bg-orange-300' },
      { label: 'Admin & fundraising', pct: 15, color: 'bg-orange-200' },
    ],
    stats: [
      { label: 'Heritage projects', value: '34' },
      { label: 'Artisans supported', value: '1,800+' },
      { label: 'Languages documented', value: '28' },
    ],
    countries: ['Ghana', 'Ethiopia', 'Mali', 'Morocco', 'Madagascar'],
    goalAmount: 200000,
    raisedAmount: 95000,
  },
  {
    slug: 'disabled',
    name: 'Disability Support',
    tagline: 'Creating inclusion where it\'s needed most',
    description: 'Advocating for and supporting people with disabilities across Africa — providing assistive devices, accessible education, livelihoods training, and community inclusion programmes.',
    icon: Accessibility,
    color: 'text-teal-600',
    bgColor: 'bg-teal-50',
    ringColor: 'ring-teal-100',
    problem: 'An estimated 80 million Africans live with disabilities. In many communities, disability carries deep stigma — children with disabilities are hidden at home, denied education, and excluded from economic life. Wheelchairs, prosthetics, and hearing aids are unaffordable.',
    approach: [
      'Assistive device provision: wheelchairs, prosthetics, hearing aids',
      'Inclusive education training for teachers and schools',
      'Disability-led enterprises with micro-loan support',
      'Community sensitization campaigns reducing stigma',
    ],
    budgetAllocation: [
      { label: 'Assistive devices', pct: 35, color: 'bg-teal-500' },
      { label: 'Inclusive education', pct: 25, color: 'bg-teal-400' },
      { label: 'Livelihoods support', pct: 20, color: 'bg-teal-300' },
      { label: 'Admin & fundraising', pct: 20, color: 'bg-teal-200' },
    ],
    stats: [
      { label: 'Devices provided', value: '4,200+' },
      { label: 'Schools made inclusive', value: '85' },
      { label: 'Disability enterprises', value: '120' },
    ],
    countries: ['Uganda', 'Kenya', 'Tanzania', 'Ghana', 'Nigeria'],
    goalAmount: 350000,
    raisedAmount: 195000,
  },
  {
    slug: 'education-and-training',
    name: 'Education & Training',
    tagline: 'Knowledge is the most powerful tool against poverty',
    description: 'Building schools, training teachers, providing learning materials, and expanding access to quality education and vocational training across underserved African communities.',
    icon: GraduationCap,
    color: 'text-violet-600',
    bgColor: 'bg-violet-50',
    ringColor: 'ring-violet-100',
    problem: 'Sub-Saharan Africa has 98 million out-of-school children — the highest number globally. Teacher shortages are severe: many rural schools have 1 teacher per 100+ students. Girls face additional barriers including period poverty and early marriage.',
    approach: [
      'School construction and rehabilitation in underserved areas',
      'Teacher recruitment, training, and ongoing mentorship',
      'Scholarship programmes for girls and vulnerable children',
      'Digital learning hubs bringing technology to rural classrooms',
    ],
    budgetAllocation: [
      { label: 'School construction', pct: 35, color: 'bg-violet-500' },
      { label: 'Teacher training', pct: 25, color: 'bg-violet-400' },
      { label: 'Scholarships', pct: 25, color: 'bg-violet-300' },
      { label: 'Admin & fundraising', pct: 15, color: 'bg-violet-200' },
    ],
    stats: [
      { label: 'Students enrolled', value: '12,800+' },
      { label: 'Teachers trained', value: '520' },
      { label: 'Schools built', value: '18' },
    ],
    countries: ['Tanzania', 'Kenya', 'Nigeria', 'Ethiopia', 'Mozambique'],
    goalAmount: 800000,
    raisedAmount: 520000,
  },
  {
    slug: 'employment-trades-and-professions',
    name: 'Employment & Skills',
    tagline: 'Creating jobs and building careers that lift families',
    description: 'Providing vocational training, apprenticeships, entrepreneurship support, and job placement services to tackle Africa\'s massive youth unemployment crisis.',
    icon: Briefcase,
    color: 'text-slate-600',
    bgColor: 'bg-slate-50',
    ringColor: 'ring-slate-100',
    problem: 'Africa\'s youth unemployment rate exceeds 30% in many countries. Even graduates struggle to find work. Millions of young people lack the vocational skills that employers need, creating a skills gap that perpetuates poverty.',
    approach: [
      'Vocational training centres teaching trades: carpentry, plumbing, coding, tailoring',
      'Apprenticeship partnerships with local businesses and industries',
      'Micro-enterprise incubation with seed funding and mentorship',
      'Job placement services connecting graduates with employers',
    ],
    budgetAllocation: [
      { label: 'Vocational training', pct: 40, color: 'bg-slate-500' },
      { label: 'Apprenticeships', pct: 25, color: 'bg-slate-400' },
      { label: 'Micro-enterprise support', pct: 20, color: 'bg-slate-300' },
      { label: 'Admin & fundraising', pct: 15, color: 'bg-slate-200' },
    ],
    stats: [
      { label: 'Youth trained', value: '6,400+' },
      { label: 'Businesses started', value: '890' },
      { label: 'Job placements', value: '2,100' },
    ],
    countries: ['Nigeria', 'South Africa', 'Kenya', 'Ghana', 'Senegal'],
    goalAmount: 450000,
    raisedAmount: 275000,
  },
  {
    slug: 'environment',
    name: 'Environment',
    tagline: 'Protecting Africa\'s land, water, and climate future',
    description: 'Fighting deforestation, restoring degraded land, promoting renewable energy, and building climate resilience in communities on the frontlines of climate change.',
    icon: Leaf,
    color: 'text-emerald-600',
    bgColor: 'bg-emerald-50',
    ringColor: 'ring-emerald-100',
    problem: 'Africa contributes less than 4% of global emissions yet suffers disproportionately from climate change. Desertification advances at 48km per year in the Sahel. 250 million Africans face water stress, and extreme weather events are increasing.',
    approach: [
      'Community-led reforestation and land restoration (Great Green Wall)',
      'Clean cookstove distribution reducing deforestation and indoor air pollution',
      'Solar energy access replacing kerosene and diesel generators',
      'Climate-smart agriculture training for smallholder farmers',
    ],
    budgetAllocation: [
      { label: 'Reforestation', pct: 35, color: 'bg-emerald-500' },
      { label: 'Renewable energy', pct: 30, color: 'bg-emerald-400' },
      { label: 'Climate-smart agriculture', pct: 20, color: 'bg-emerald-300' },
      { label: 'Admin & fundraising', pct: 15, color: 'bg-emerald-200' },
    ],
    stats: [
      { label: 'Trees planted', value: '2.4M' },
      { label: 'Clean cookstoves distributed', value: '18,500' },
      { label: 'Solar installations', value: '120' },
    ],
    countries: ['Niger', 'Mali', 'Senegal', 'Kenya', 'Ethiopia'],
    goalAmount: 550000,
    raisedAmount: 340000,
  },
  {
    slug: 'family',
    name: 'Family Support',
    tagline: 'Strengthening the families that hold communities together',
    description: 'Supporting African families through parenting programmes, domestic violence prevention, foster care systems, family reunification, and household economic strengthening.',
    icon: Home,
    color: 'text-pink-600',
    bgColor: 'bg-pink-50',
    ringColor: 'ring-pink-100',
    problem: 'Family breakdown driven by poverty, HIV/AIDS, migration, and conflict has left millions of African children in vulnerable care arrangements. Domestic violence rates remain high, and single caregivers — predominantly women — struggle to support households alone.',
    approach: [
      'Family strengthening programmes keeping children with their families',
      'Domestic violence prevention and survivor support services',
      'Foster care development and caregiver support groups',
      'Economic empowerment for female-headed households',
    ],
    budgetAllocation: [
      { label: 'Family programmes', pct: 40, color: 'bg-pink-500' },
      { label: 'GBV prevention', pct: 25, color: 'bg-pink-400' },
      { label: 'Economic empowerment', pct: 20, color: 'bg-pink-300' },
      { label: 'Admin & fundraising', pct: 15, color: 'bg-pink-200' },
    ],
    stats: [
      { label: 'Families supported', value: '5,600+' },
      { label: 'Survivors sheltered', value: '1,200' },
      { label: 'Caregivers trained', value: '3,400' },
    ],
    countries: ['South Africa', 'Kenya', 'Uganda', 'Zimbabwe', 'Ghana'],
    goalAmount: 350000,
    raisedAmount: 210000,
  },
  {
    slug: 'health',
    name: 'Healthcare',
    tagline: 'Bringing quality healthcare to every community',
    description: 'Funding clinics, training health workers, providing essential medicines, and running mobile health units that reach the most remote communities across Africa.',
    icon: Stethoscope,
    color: 'text-savanna',
    bgColor: 'bg-savanna/10',
    ringColor: 'ring-savanna/20',
    problem: 'Africa carries 25% of the global disease burden but has only 3% of the world\'s health workers. In rural areas, the ratio can be 1 doctor per 50,000 people. Maternal mortality, malaria, and preventable diseases remain devastatingly common.',
    approach: [
      'Community health worker training and deployment in rural areas',
      'Essential medicine supply chains and clinic stocking',
      'Mobile health units reaching remote villages on scheduled routes',
      'Maternal and child health programmes with skilled birth attendants',
    ],
    budgetAllocation: [
      { label: 'Health worker training', pct: 30, color: 'bg-savanna' },
      { label: 'Medicines & supplies', pct: 30, color: 'bg-savanna/80' },
      { label: 'Mobile clinics', pct: 25, color: 'bg-savanna/60' },
      { label: 'Admin & fundraising', pct: 15, color: 'bg-savanna/40' },
    ],
    stats: [
      { label: 'Patients treated', value: '45,000+' },
      { label: 'Health workers trained', value: '680' },
      { label: 'Mobile clinic visits', value: '12,000' },
    ],
    countries: ['Tanzania', 'Mozambique', 'Malawi', 'Uganda', 'DRC'],
    goalAmount: 750000,
    raisedAmount: 480000,
  },
  {
    slug: 'hearing-impairments',
    name: 'Hearing Impairments',
    tagline: 'Breaking the silence for Africa\'s deaf community',
    description: 'Providing hearing aids, sign language training, deaf education, and advocacy for the millions of Africans living with hearing loss who have no access to audiological care.',
    icon: Ear,
    color: 'text-cyan-600',
    bgColor: 'bg-cyan-50',
    ringColor: 'ring-cyan-100',
    problem: 'An estimated 40 million Africans have hearing loss, yet fewer than 10% have access to hearing aids. Deaf children are often denied education entirely, excluded from community life, and stigmatised. There are fewer than 200 audiologists in all of sub-Saharan Africa.',
    approach: [
      'Hearing aid provision and maintenance programmes',
      'Sign language training for families, teachers, and communities',
      'Deaf education schools and inclusive classroom training',
      'Advocacy for deaf rights and accessibility standards',
    ],
    budgetAllocation: [
      { label: 'Hearing aids', pct: 35, color: 'bg-cyan-500' },
      { label: 'Sign language training', pct: 25, color: 'bg-cyan-400' },
      { label: 'Deaf education', pct: 25, color: 'bg-cyan-300' },
      { label: 'Admin & fundraising', pct: 15, color: 'bg-cyan-200' },
    ],
    stats: [
      { label: 'Hearing aids provided', value: '2,800+' },
      { label: 'Sign language learners', value: '4,500' },
      { label: 'Deaf children in school', value: '620' },
    ],
    countries: ['Kenya', 'Nigeria', 'Uganda', 'Ghana', 'Tanzania'],
    goalAmount: 300000,
    raisedAmount: 145000,
  },
  {
    slug: 'hospices',
    name: 'Hospices & Palliative Care',
    tagline: 'Ensuring no one faces their final days alone or in pain',
    description: 'Providing compassionate end-of-life care, pain management, and family bereavement support in communities where palliative care services are virtually non-existent.',
    icon: Bed,
    color: 'text-lavender-600',
    bgColor: 'bg-purple-50',
    ringColor: 'ring-purple-100',
    problem: 'Over 1 million Africans need palliative care each year, but less than 5% receive it. Most countries have fewer than 10 palliative care providers. Cancer, HIV/AIDS, and other terminal conditions cause enormous suffering without pain management.',
    approach: [
      'Home-based palliative care with trained community health workers',
      'Essential pain medication access and palliative medicine training',
      'Bereavement counselling and family support services',
      'Community education destigmatising death, dying, and pain relief',
    ],
    budgetAllocation: [
      { label: 'Home-based care', pct: 40, color: 'bg-purple-500' },
      { label: 'Pain management', pct: 25, color: 'bg-purple-400' },
      { label: 'Family support', pct: 20, color: 'bg-purple-300' },
      { label: 'Admin & fundraising', pct: 15, color: 'bg-purple-200' },
    ],
    stats: [
      { label: 'Patients cared for', value: '3,200+' },
      { label: 'Families supported', value: '8,500' },
      { label: 'Community carers trained', value: '280' },
    ],
    countries: ['Kenya', 'Uganda', 'Tanzania', 'South Africa', 'Zimbabwe'],
    goalAmount: 250000,
    raisedAmount: 130000,
  },
  {
    slug: 'hospitals',
    name: 'Hospital Support',
    tagline: 'Equipping the hospitals that save lives every day',
    description: 'Providing medical equipment, supplies, infrastructure improvements, and staff training to under-resourced hospitals and health centres across Africa.',
    icon: Building2,
    color: 'text-red-600',
    bgColor: 'bg-red-50',
    ringColor: 'ring-red-100',
    problem: 'Many African hospitals operate with critically outdated equipment, drug shortages, and crumbling infrastructure. Surgeons perform operations by phone light. Maternity wards lack basic delivery equipment. Post-operative infection rates remain dangerously high.',
    approach: [
      'Medical equipment procurement and installation',
      'Hospital infrastructure upgrades: water, electricity, waste management',
      'Specialist staff training programmes and mentorship',
      'Supply chain management for essential drugs and consumables',
    ],
    budgetAllocation: [
      { label: 'Medical equipment', pct: 35, color: 'bg-red-500' },
      { label: 'Infrastructure', pct: 30, color: 'bg-red-400' },
      { label: 'Staff training', pct: 20, color: 'bg-red-300' },
      { label: 'Admin & fundraising', pct: 15, color: 'bg-red-200' },
    ],
    stats: [
      { label: 'Hospitals supported', value: '24' },
      { label: 'Equipment donated', value: '340+' },
      { label: 'Staff trained', value: '1,100' },
    ],
    countries: ['Ghana', 'Nigeria', 'Tanzania', 'DRC', 'Mozambique'],
    goalAmount: 600000,
    raisedAmount: 350000,
  },
  {
    slug: 'housing',
    name: 'Housing & Shelter',
    tagline: 'A safe home is the foundation of everything',
    description: 'Building safe, durable, and affordable housing for families living in informal settlements, displacement camps, and communities devastated by poverty or natural disasters.',
    icon: Home,
    color: 'text-yellow-600',
    bgColor: 'bg-yellow-50',
    ringColor: 'ring-yellow-100',
    problem: 'Africa faces a housing deficit of over 50 million units. Over 200 million Africans live in slums or informal settlements without secure tenure, clean water, sanitation, or structural safety. Displacement from conflict affects over 30 million.',
    approach: [
      'Community-driven housing construction using local materials and labour',
      'Land rights advocacy and secure tenure programmes',
      'Disaster-resilient building training for communities',
      'Temporary and transitional shelter for displaced families',
    ],
    budgetAllocation: [
      { label: 'Construction materials', pct: 40, color: 'bg-yellow-500' },
      { label: 'Labour & training', pct: 25, color: 'bg-yellow-400' },
      { label: 'Land rights advocacy', pct: 15, color: 'bg-yellow-300' },
      { label: 'Admin & fundraising', pct: 20, color: 'bg-yellow-200' },
    ],
    stats: [
      { label: 'Homes built', value: '480+' },
      { label: 'Families housed', value: '480' },
      { label: 'Communities upgraded', value: '15' },
    ],
    countries: ['South Africa', 'Kenya', 'Nigeria', 'Rwanda', 'Uganda'],
    goalAmount: 500000,
    raisedAmount: 290000,
  },
  {
    slug: 'human-rights',
    name: 'Human Rights',
    tagline: 'Standing up for justice, dignity, and equality',
    description: 'Defending fundamental human rights across Africa — fighting for freedom of expression, gender equality, LGBTQ+ rights, refugee protection, and an end to extrajudicial violence.',
    icon: HandHeart,
    color: 'text-blue-600',
    bgColor: 'bg-blue-50',
    ringColor: 'ring-blue-100',
    problem: 'Human rights abuses remain widespread across many African nations: arbitrary detention, extrajudicial killings, restrictions on press freedom, forced displacement, child marriage, and FGM. Civil society space is shrinking in several countries.',
    approach: [
      'Legal aid clinics providing free representation to rights defenders',
      'Community human rights education and awareness programmes',
      'Documentation and advocacy on systemic violations',
      'Emergency protection for activists, journalists, and refugees',
    ],
    budgetAllocation: [
      { label: 'Legal aid', pct: 35, color: 'bg-blue-500' },
      { label: 'Community education', pct: 25, color: 'bg-blue-400' },
      { label: 'Emergency protection', pct: 20, color: 'bg-blue-300' },
      { label: 'Admin & fundraising', pct: 20, color: 'bg-blue-200' },
    ],
    stats: [
      { label: 'Legal cases won', value: '340+' },
      { label: 'Communities educated', value: '1,200' },
      { label: 'Activists protected', value: '85' },
    ],
    countries: ['Nigeria', 'Uganda', 'DRC', 'Zimbabwe', 'Sudan'],
    goalAmount: 400000,
    raisedAmount: 210000,
  },
  {
    slug: 'international',
    name: 'International Aid',
    tagline: 'Coordinating global generosity for maximum local impact',
    description: 'Channeling international donations and expertise into high-impact programmes across multiple African countries, coordinating with local partners for scale and sustainability.',
    icon: Globe2,
    color: 'text-ochre',
    bgColor: 'bg-ochre/10',
    ringColor: 'ring-ochre/20',
    problem: 'While billions flow into Africa annually, much is poorly coordinated, fragmented, and disconnected from community needs. Duplication wastes resources while the most vulnerable communities receive nothing.',
    approach: [
      'Multi-country programme coordination reducing duplication',
      'Local partner capacity building for sustainable delivery',
      'Rapid response coordination for emerging crises',
      'South-South learning exchanges between African countries',
    ],
    budgetAllocation: [
      { label: 'Programme delivery', pct: 50, color: 'bg-ochre' },
      { label: 'Partner capacity building', pct: 20, color: 'bg-ochre/80' },
      { label: 'Coordination & M&E', pct: 15, color: 'bg-ochre/60' },
      { label: 'Admin & fundraising', pct: 15, color: 'bg-ochre/40' },
    ],
    stats: [
      { label: 'Countries reached', value: '12' },
      { label: 'Local partners', value: '45' },
      { label: 'Lives impacted', value: '85,000+' },
    ],
    countries: ['Pan-African'],
    goalAmount: 1000000,
    raisedAmount: 620000,
  },
  {
    slug: 'learning-disabilities-and-sen',
    name: 'Learning Disabilities & SEN',
    tagline: 'Every mind deserves the chance to flourish',
    description: 'Supporting children and adults with learning disabilities, ADHD, autism spectrum conditions, and special educational needs across Africa through diagnosis, therapy, and inclusive education.',
    icon: BookOpen,
    color: 'text-fuchsia-600',
    bgColor: 'bg-fuchsia-50',
    ringColor: 'ring-fuchsia-100',
    problem: 'Learning disabilities are massively underdiagnosed across Africa. Children with ADHD, autism, dyslexia, and intellectual disabilities are often labelled "slow" or "cursed" and denied education. There are fewer than 500 special needs educators in most African countries.',
    approach: [
      'Screening and diagnostic programmes in schools and communities',
      'Therapeutic interventions: occupational therapy, speech therapy, counselling',
      'Teacher training on inclusive education and differentiated instruction',
      'Parent support groups and disability awareness campaigns',
    ],
    budgetAllocation: [
      { label: 'Screening & diagnosis', pct: 25, color: 'bg-fuchsia-500' },
      { label: 'Therapy services', pct: 35, color: 'bg-fuchsia-400' },
      { label: 'Teacher training', pct: 25, color: 'bg-fuchsia-300' },
      { label: 'Admin & fundraising', pct: 15, color: 'bg-fuchsia-200' },
    ],
    stats: [
      { label: 'Children screened', value: '8,400+' },
      { label: 'Teachers trained', value: '420' },
      { label: 'Therapy sessions', value: '15,000' },
    ],
    countries: ['South Africa', 'Kenya', 'Nigeria', 'Ghana', 'Uganda'],
    goalAmount: 350000,
    raisedAmount: 180000,
  },
  {
    slug: 'medical-research',
    name: 'Medical Research',
    tagline: 'Finding cures for the diseases that hit Africa hardest',
    description: 'Funding research into diseases disproportionately affecting Africa — malaria, tuberculosis, sickle cell disease, Ebola, and neglected tropical diseases — led by African researchers.',
    icon: Microscope,
    color: 'text-sky-700',
    bgColor: 'bg-sky-50',
    ringColor: 'ring-sky-100',
    problem: 'Africa bears 25% of the global disease burden but receives less than 1% of global health research funding. Diseases like sickle cell anaemia, malaria, and sleeping sickness lack adequate treatment because they primarily affect the global poor.',
    approach: [
      'Grants for African-led medical research institutions',
      'Clinical trial infrastructure and community engagement',
      'Scholarships training the next generation of African researchers',
      'Research-to-policy translation ensuring findings reach patients',
    ],
    budgetAllocation: [
      { label: 'Research grants', pct: 45, color: 'bg-sky-600' },
      { label: 'Infrastructure', pct: 25, color: 'bg-sky-500' },
      { label: 'Scholarships', pct: 15, color: 'bg-sky-400' },
      { label: 'Admin & fundraising', pct: 15, color: 'bg-sky-300' },
    ],
    stats: [
      { label: 'Research projects funded', value: '32' },
      { label: 'Researchers supported', value: '145' },
      { label: 'Papers published', value: '78' },
    ],
    countries: ['South Africa', 'Nigeria', 'Kenya', 'Ghana', 'Ethiopia'],
    goalAmount: 500000,
    raisedAmount: 280000,
  },
  {
    slug: 'medical-welfare',
    name: 'Medical Welfare',
    tagline: 'Making healthcare accessible when no one else will',
    description: 'Providing medical assistance, health insurance support, and financial aid for treatment to vulnerable individuals and families who cannot afford healthcare across Africa.',
    icon: Pill,
    color: 'text-orange-700',
    bgColor: 'bg-orange-50',
    ringColor: 'ring-orange-100',
    problem: 'Out-of-pocket healthcare spending pushes over 15 million Africans into poverty every year. Families sell livestock, land, and possessions to pay for surgeries and treatments. Many simply go without care and die from treatable conditions.',
    approach: [
      'Medical expense funds covering surgeries, treatments, and medications',
      'Community health insurance schemes with subsidised premiums',
      'Healthcare navigation helping families access available services',
      'Emergency medical transport reaching patients in remote areas',
    ],
    budgetAllocation: [
      { label: 'Treatment funding', pct: 45, color: 'bg-orange-600' },
      { label: 'Health insurance subsidies', pct: 25, color: 'bg-orange-500' },
      { label: 'Healthcare navigation', pct: 15, color: 'bg-orange-400' },
      { label: 'Admin & fundraising', pct: 15, color: 'bg-orange-300' },
    ],
    stats: [
      { label: 'Patients funded', value: '2,800+' },
      { label: 'Families insured', value: '4,200' },
      { label: 'Emergency transports', value: '560' },
    ],
    countries: ['Nigeria', 'Ghana', 'Kenya', 'Tanzania', 'Senegal'],
    goalAmount: 400000,
    raisedAmount: 230000,
  },
  {
    slug: 'mental-health',
    name: 'Mental Health',
    tagline: 'Breaking the silence around mental illness in Africa',
    description: 'Providing mental health services, training community counsellors, running anti-stigma campaigns, and building mental health infrastructure in communities where psychiatric care barely exists.',
    icon: Brain,
    color: 'text-violet-700',
    bgColor: 'bg-violet-50',
    ringColor: 'ring-violet-100',
    problem: 'Africa has fewer than 0.1 psychiatrists per 100,000 people (compared to 16 in Europe). Depression, anxiety, PTSD, and substance abuse affect millions but go untreated due to stigma, lack of services, and shortage of trained professionals.',
    approach: [
      'Community mental health worker training and deployment',
      'Anti-stigma campaigns using media, theatre, and community dialogue',
      'Psychosocial support groups for depression, anxiety, and trauma',
      'Integration of mental health into primary healthcare systems',
    ],
    budgetAllocation: [
      { label: 'Mental health workers', pct: 35, color: 'bg-violet-600' },
      { label: 'Counselling services', pct: 30, color: 'bg-violet-500' },
      { label: 'Anti-stigma campaigns', pct: 15, color: 'bg-violet-400' },
      { label: 'Admin & fundraising', pct: 20, color: 'bg-violet-300' },
    ],
    stats: [
      { label: 'Patients supported', value: '6,200+' },
      { label: 'Counsellors trained', value: '380' },
      { label: 'Community sessions', value: '2,400' },
    ],
    countries: ['South Africa', 'Nigeria', 'Kenya', 'Uganda', 'Ghana'],
    goalAmount: 350000,
    raisedAmount: 190000,
  },
  {
    slug: 'overseas-aid',
    name: 'Overseas Aid & Relief',
    tagline: 'Delivering hope where disaster and poverty strike hardest',
    description: 'Providing emergency relief, humanitarian aid, and long-term development support to the most vulnerable communities across Africa during and after crises.',
    icon: Plane,
    color: 'text-indigo-700',
    bgColor: 'bg-indigo-50',
    ringColor: 'ring-indigo-100',
    problem: 'Africa experiences over 100 natural disasters and complex emergencies annually. Over 40 million people are internally displaced. Humanitarian response is chronically underfunded — the UN regularly appeals for billions that are never donated.',
    approach: [
      'Emergency shelter, food, water, and medical supplies within 72 hours',
      'Long-term recovery programmes rebuilding livelihoods post-crisis',
      'Pre-positioned emergency supplies in disaster-prone regions',
      'Community disaster preparedness training reducing future impact',
    ],
    budgetAllocation: [
      { label: 'Emergency relief', pct: 40, color: 'bg-indigo-600' },
      { label: 'Long-term recovery', pct: 30, color: 'bg-indigo-500' },
      { label: 'Preparedness', pct: 15, color: 'bg-indigo-400' },
      { label: 'Admin & fundraising', pct: 15, color: 'bg-indigo-300' },
    ],
    stats: [
      { label: 'People reached', value: '42,000+' },
      { label: 'Emergency responses', value: '18' },
      { label: 'Countries served', value: '8' },
    ],
    countries: ['Mozambique', 'Somalia', 'Sudan', 'DRC', 'Ethiopia'],
    goalAmount: 800000,
    raisedAmount: 490000,
  },
  {
    slug: 'religious',
    name: 'Faith-Based Organisations',
    tagline: 'Faith in action serving communities across Africa',
    description: 'Supporting faith-based organisations and interfaith initiatives providing education, healthcare, food, and community support across Africa regardless of religious affiliation.',
    icon: Church,
    color: 'text-stone-600',
    bgColor: 'bg-stone-50',
    ringColor: 'ring-stone-100',
    problem: 'Faith-based organisations deliver up to 40% of healthcare and 60% of education in some African countries, yet receive limited funding for infrastructure and sustainability. They often serve areas no government or NGO reaches.',
    approach: [
      'Infrastructure grants for schools, clinics, and community centres run by FBOs',
      'Training and capacity building for faith-based leaders and workers',
      'Interfaith peace-building programmes reducing community tensions',
      'Sustainability planning helping FBOs diversify income beyond donations',
    ],
    budgetAllocation: [
      { label: 'Infrastructure grants', pct: 40, color: 'bg-stone-500' },
      { label: 'Training programmes', pct: 25, color: 'bg-stone-400' },
      { label: 'Peace-building', pct: 15, color: 'bg-stone-300' },
      { label: 'Admin & fundraising', pct: 20, color: 'bg-stone-200' },
    ],
    stats: [
      { label: 'Organisations supported', value: '120+' },
      { label: 'Communities served', value: '350' },
      { label: 'Leaders trained', value: '580' },
    ],
    countries: ['Pan-African'],
    goalAmount: 300000,
    raisedAmount: 175000,
  },
  {
    slug: 'rescue-services',
    name: 'Rescue & Emergency Services',
    tagline: 'First responders saving lives when every second counts',
    description: 'Training, equipping, and supporting community-based rescue services, first responders, and emergency teams in areas where professional emergency services don\'t exist.',
    icon: Truck,
    color: 'text-red-700',
    bgColor: 'bg-red-50',
    ringColor: 'ring-red-100',
    problem: 'Most rural African communities have no access to ambulances, fire services, or trained first responders. Road traffic accidents, burns, drowning, and injuries kill millions who could have survived with timely basic first aid.',
    approach: [
      'Community first responder training and certification',
      'Emergency equipment provision: stretchers, oxygen, first aid kits',
      'Motorcycle ambulance networks reaching remote villages',
      'Emergency dispatch and coordination systems',
    ],
    budgetAllocation: [
      { label: 'Training programmes', pct: 30, color: 'bg-red-600' },
      { label: 'Equipment provision', pct: 35, color: 'bg-red-500' },
      { label: 'Ambulance networks', pct: 20, color: 'bg-red-400' },
      { label: 'Admin & fundraising', pct: 15, color: 'bg-red-300' },
    ],
    stats: [
      { label: 'First responders trained', value: '2,400+' },
      { label: 'Lives saved', value: '1,800' },
      { label: 'Motorcycle ambulances', value: '65' },
    ],
    countries: ['Kenya', 'Tanzania', 'Uganda', 'Ghana', 'Nigeria'],
    goalAmount: 350000,
    raisedAmount: 200000,
  },
  {
    slug: 'social-welfare',
    name: 'Social Welfare',
    tagline: 'A safety net for Africa\'s most vulnerable people',
    description: 'Providing social protection, welfare support, and advocacy for vulnerable groups including the homeless, refugees, people in poverty, and those affected by substance abuse.',
    icon: UsersRound,
    color: 'text-teal-700',
    bgColor: 'bg-teal-50',
    ringColor: 'ring-teal-100',
    problem: 'Social protection coverage in Africa averages only 18% — compared to 70% in Europe. Millions lack access to social services, welfare programmes, or any safety net. Homelessness, substance abuse, and extreme poverty remain rampant in urban and rural areas.',
    approach: [
      'Social work case management for vulnerable individuals and families',
      'Rehabilitation programmes for substance abuse and addiction',
      'Homeless shelter operations and reintegration support',
      'Policy advocacy for expanded social protection systems',
    ],
    budgetAllocation: [
      { label: 'Direct support', pct: 40, color: 'bg-teal-600' },
      { label: 'Rehabilitation', pct: 25, color: 'bg-teal-500' },
      { label: 'Policy advocacy', pct: 15, color: 'bg-teal-400' },
      { label: 'Admin & fundraising', pct: 20, color: 'bg-teal-300' },
    ],
    stats: [
      { label: 'People supported', value: '8,600+' },
      { label: 'Rehabilitated', value: '1,400' },
      { label: 'Policy wins', value: '6' },
    ],
    countries: ['South Africa', 'Nigeria', 'Kenya', 'Ethiopia', 'Ghana'],
    goalAmount: 350000,
    raisedAmount: 210000,
  },
  {
    slug: 'sport-and-recreation',
    name: 'Sport & Recreation',
    tagline: 'Using sport to build healthier, stronger communities',
    description: 'Harnessing the power of sport and physical activity for community health, youth development, social cohesion, and life skills training across Africa.',
    icon: Dumbbell,
    color: 'text-lime-600',
    bgColor: 'bg-lime-50',
    ringColor: 'ring-lime-100',
    problem: 'Physical inactivity is rising rapidly in Africa as urbanisation increases. Youth unemployment, gang involvement, and substance abuse thrive where there are no recreational facilities. Sport has proven power to transform communities but receives minimal investment.',
    approach: [
      'Community sports facility construction and maintenance',
      'Youth sport leagues with life skills education embedded',
      'Women\'s sport programmes breaking gender barriers',
      'Coach and referee training creating local employment',
    ],
    budgetAllocation: [
      { label: 'Facility construction', pct: 35, color: 'bg-lime-500' },
      { label: 'Youth programmes', pct: 30, color: 'bg-lime-400' },
      { label: 'Coach training', pct: 15, color: 'bg-lime-300' },
      { label: 'Admin & fundraising', pct: 20, color: 'bg-lime-200' },
    ],
    stats: [
      { label: 'Youth engaged', value: '9,200+' },
      { label: 'Facilities built', value: '22' },
      { label: 'Coaches trained', value: '180' },
    ],
    countries: ['South Africa', 'Nigeria', 'Kenya', 'Ghana', 'Senegal'],
    goalAmount: 250000,
    raisedAmount: 140000,
  },
  {
    slug: 'visual-impairments',
    name: 'Visual Impairments',
    tagline: 'Restoring sight and creating a world that sees everyone',
    description: 'Preventing blindness, providing eye care, distributing reading materials in accessible formats, and advocating for the rights of visually impaired people across Africa.',
    icon: Eye,
    color: 'text-rose-700',
    bgColor: 'bg-rose-50',
    ringColor: 'ring-rose-100',
    problem: 'Africa has the highest rates of preventable blindness globally. Over 20 million Africans are visually impaired, yet cataract surgery — which takes 15 minutes and costs $50 — remains inaccessible. School-age children with vision loss are often dropped from education entirely.',
    approach: [
      'Free cataract surgeries and eye camp programmes',
      'School eye screening and glasses distribution',
      'Braille literacy and assistive technology training',
      'Community eye health education and vitamin A supplementation',
    ],
    budgetAllocation: [
      { label: 'Surgical programmes', pct: 35, color: 'bg-rose-600' },
      { label: 'School screenings', pct: 25, color: 'bg-rose-500' },
      { label: 'Braille & assistive tech', pct: 20, color: 'bg-rose-400' },
      { label: 'Admin & fundraising', pct: 20, color: 'bg-rose-300' },
    ],
    stats: [
      { label: 'Surgeries performed', value: '4,800+' },
      { label: 'Children screened', value: '32,000' },
      { label: 'Braille materials', value: '12,000' },
    ],
    countries: ['Nigeria', 'Ghana', 'Kenya', 'Tanzania', 'Ethiopia'],
    goalAmount: 400000,
    raisedAmount: 240000,
  },
]

export function getCategoryBySlug(slug: string): Category | undefined {
  return categories.find((c) => c.slug === slug)
}
