---
deployment:
  tasks:
    - export FRONTPATH=/home2/datingsi/givetoafrica.net/
    - export BACKENDPATH=/home2/datingsi/backend/
    - cp -R dist/. $FRONTPATH
    - cp -R dist/server/. $BACKENDPATH
    - cp -R prisma $BACKENDPATH
    - cp package.json $BACKENDPATH
